### ISSUE TITLE
Misc type "other" is wrong in OAI

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1061] opened 2023-04-13 07:34 UTC
# Bug description
Misc type "other" is wrong in OAI.

When selecting "Publication type = miscellaneous" and "Miscellaneous type = - ":

It now says
```
<genre authority="ugent" type="biblio">misc</genre>
<genre authority="ugent" type="article">original</genre>
```

Should be
 ```
<genre authority="ugent" type="biblio">misc</genre>
<genre authority="ugent" type="misc">other</genre>
```

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/publication/01GM8M9JEZSTWNWECPGDRFA2BY?redirect-url=%2Fpublication%3Fq%3D01GM8M9JEZSTWNWECPGDRFA2BY%26sort%3Ddate-updated-desc and see

Publication type "Miscellaneous"
Miscellaneous type "-" 

<img width="393" alt="Scherm­afbeelding 2023-04-13 om 09 28 10" src="https://user-images.githubusercontent.com/1572885/231685782-e3af91bb-32e5-4c71-82dd-424d0fc2eddf.png">

2. Check on OAI output: https://biblio.ugent.be/oai?verb=GetRecord&identifier=01GM8M9JEZSTWNWECPGDRFA2BY&metadataPrefix=mods_36 and see

Biblio type (Publication type) "misc"
Article type "original"

<img width="954" alt="Scherm­afbeelding 2023-04-13 om 09 33 05" src="https://user-images.githubusercontent.com/1572885/231687020-5abdefd4-9f21-4c6f-a268-a7307764414e.png">

Should be

Biblio type (Publication type) "misc"
Miscellaneous type "other"

Presents itself with following records:
- 01GM8M9JEZSTWNWECPGDRFA2BY
- 01GMAFEKEAA54GEVWFW8JT8M3J
- 01GMAFTSVRYAMRT0Q4E6KA2S1P
- 01GMAFQ764T9GYKFD32QKDSMPN

**Comment by nics** [comment] 2023-04-13 08:31
it's a data error, these records have type misc + article_type original, i'll clean them up

**Comment by mietcls** [comment] 2023-04-13 09:08
Thank you!

**Comment by nics** [comment] 2023-04-13 09:26
subtype was not cleared after type change, fixed by https://github.com/ugent-library/biblio-backoffice/commit/9956340a84e31f03772c499b3abad761493b7d1e

**Comment by mietcls** [comment] 2023-04-13 09:48
Do I follow up and check whether the fix comes through after deploy, or is it as intended that the misc type is now removed?
https://biblio.ugent.be/oai?verb=GetRecord&identifier=01GMAFQ764T9GYKFD32QKDSMPN&metadataPrefix=mods_36
<img width="666" alt="Scherm­afbeelding 2023-04-13 om 11 47 02" src="https://user-images.githubusercontent.com/1572885/231721777-39cee7e6-1e72-48b7-af64-888a982027b6.png">

**Comment by nics** [comment] 2023-04-13 09:50
@miet as intended, misc type was not set in the records

**Closed** 2023-04-13 10:28 UTC
Labels: bug
